CC = gcc
CFLAGS = -Wall -Wextra -pedantic
TARGET = myshell
SRC_DIR = src
SRCS = $(SRC_DIR)/shell.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean